language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "nightly"
# command to install dependencies
before_install:
  # - python --version
  # - pip install -U pip
  # - pip install -U pytest
  - pip install codecov
install:
  - pip install -r requirements.txt

# command to run tests
script:
  python -m pytest test/

# no emails, I can check it myself, thank you
notifications:
  email: false
