language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"
  - "nightly"

arch:
  - amd64
  - arm64

# command to install dependencies

before_install:
  - pip install --upgrade pip setuptools wheel

install:
  - pip install coverage
  - pip install -r requirements.txt

jobs:
  include:
    - stage: "Extra packages"
      name: "Testing extra packages"
      python: 3.6
      install:
        - pip install coverage
        - pip install -r requirements.txt
        - pip install EMD-signal
      script:
        - coverage run -m pytest test/test_EMD.py
        - coverage run -m pytest test/test_MFDFA_extras.py
  allow_failures:
    - python: "nightly"


script:
  - coverage run -m pytest test/test_fgn.py
  - coverage run -m pytest test/test_MFDFA.py

after_success:
  bash <(curl -s https://codecov.io/bash)

# no emails, I can check it myself, thank you
notifications:
  email: false
